ARG CLEANUP="yes"
FROM centos:7 AS base
ARG MAKE_DOCS="no"

RUN yum update -y && \
    yum install -y autoconf automake bzip2 bzip2-devel freetype-devel gcc gcc-c++ git libtool make mercurial && \
    yum install -y vim

#      yum install autoconf automake bzip2 bzip2-devel cmake freetype-devel gcc gcc-c++ git libtool make mercurial pkgconfig zlib-devel

WORKDIR /app
COPY ./build-ffmpeg /app/build-ffmpeg

RUN STOP_BEFORE_CMAKE=yes /app/build-ffmpeg --build
RUN SKIP_FFMPEG_BUILD=yes /app/build-ffmpeg --build
RUN AUTOINSTALL=yes /app/build-ffmpeg --build  # toggle comment to trigger layer rebuild
RUN cp /app/workspace/bin/ffmpeg /app/workspace/bin/ffprobe /usr/bin/

FROM base as cleanup-no
FROM base as cleanup-yes
RUN /app/build-ffmpeg --cleanup

FROM cleanup-${CLEANUP} AS final

CMD         ["--help"]
ENTRYPOINT  ["/usr/bin/ffmpeg"]
